### ISSUE TITLE
"ValueError" with latest `products` script

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#26]
Tried with test data available here: https://github.com/ARPA-SIMC/qc_sample_data/tree/master/satellite/hrit

```
$ /home/branco/git/meteosatlib/examples/products -t 202002231200 -s /home/branco/buttami/qc_sample_data/satellite/hrit/ --warp='-t_srs "+proj=latlong" -te -10 30 30 60' -d ../ --cachedir=/tmp/ --msat=MSG4
Traceback (most recent call last):
  File "/home/branco/git/meteosatlib/examples/products", line 883, in <module>
    sat.make_product(prod, args.format, args.shp, destdir=args.destdir)
  File "/home/branco/git/meteosatlib/examples/products", line 252, in make_product
    res = maker.compute()
  File "/home/branco/git/meteosatlib/examples/products", line 723, in compute
    return upscaledr * hrvnorm, upscaledg * hrvnorm, upscaledb * hrvnorm
ValueError: operands could not be broadcast together with shapes (716,955) (2105,2806)
```

**Comment by spanezz** [comment]
Confirmed, I managed to reproduce it

**Comment by spanezz** [comment]
Ok, losing imresize (see #23) we need a function that does both contrast stretch and occasionally image resize.

The [imresize implementation](https://github.com/scipy/scipy/blob/v1.2.1/scipy/misc/pilutil.py) did a lot of work. We unfortunately cannot use [skimage](https://scikit-image.org/) because, as usual, of Centos.

I'll try to retrofit a custom implementation, and I cannot guarantee there won't be a little loss of image quality as a consequence of "custom": it's not really my field.

**Comment by brancomat** [comment]
After some analysis, the best option would be if the `products` script could test for `imresize`or `skimage` presence, and then use the one that's present in the system.
